openapi: '3.0.2'
info:
  title: Firefly
  version: '1.0'
servers:
  - url: http://localhost:5000/api/v1
paths:  
  /network/self:
    put:
      description: Initiate self-registration of this Firefly node
      operationId: putNetworkSelf
      requestBody:
         content:
           application/json:
              schema:
                $ref: '#/components/schemas/putNetworkSelfInput'
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/putNetworkSelfOutput'
  /network/identities:
    put:
      description: Initiate registration of an identity owned by this node
      operationId: putNetworkIdentity
      requestBody:
         content:
           application/json:
              schema:
                $ref: '#/components/schemas/putNetworkIdentityInput'
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/putNetworkIdentityOutput'
  /ns/{namespace}/defs/datatypes/{name}:
    put:
      description: Initiate registration of an identity owned by this node
      operationId: putDefsDatatypes
      parameters:
        - $ref: '#/components/parameters/namespace'
        - $ref: '#/components/parameters/name'
      requestBody:
         content:
           application/json:
              schema:
                $ref: '#/components/schemas/putNetworkIdentityInput'
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/putNetworkIdentityOutput'                
components:
  parameters:
    namespace:
      name: namespace
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/fireflyObjectName'
    name:
      name: name
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/fireflyObjectName'
  schemas:
    fireflyObjectName:
      description: |
        A case sensitive string up to 64 chars long, starting and ending with an alphanumeric (a-zA-Z0-9),
        containing alphanumerics, dots (.), dashes (-) and underscores (_).
      type: string
      pattern: '[a-zA-Z0-9]([a-zA-Z0-9_.-]*[a-zA-Z0-9])?$'
      maxLength: 64         
    putNetworkSelfInput:
      properties: {}
      additionalProperties: false
    putNetworkSelfOutput:
      properties: {}
      additionalProperties: false
    putNetworkIdentityInput:
      properties: {}
      additionalProperties: false
    putNetworkIdentityOutput:
      properties: {}
      additionalProperties: false