{{- if and .Values.dataexchange.enabled .Values.dataexchange.ingress.enabled -}}
{{- $fullName := include "firefly.fullname" . -}}
{{- $svcPort := .Values.dataexchange.service.p2pPort -}}
{{- if and .Values.dataexchange.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.dataexchange.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.dataexchange.ingress.annotations "kubernetes.io/ingress.class" .Values.dataexchange.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-dx
  labels:
    {{- include "firefly.labels" . | nindent 4 }}
  {{- with .Values.dataexchange.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.dataexchange.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.dataexchange.ingress.className }}
  {{- end }}
  {{- $tlsSecretName := .Values.dataexchange.tlsSecret.name }}
  {{- if and .Values.dataexchange.certificate.enabled (not .Values.dataexchange.tlsSecret.enabled) }}
  {{- $tlsSecretName = printf "%s-dx-tls" $fullName}}
  {{- end }}
  tls:
    - hosts:
        {{- range .Values.dataexchange.ingress.hosts }}
        - {{ .host | quote }}
        {{- end }}
      secretName: {{ $tlsSecretName }}
  rules:
    {{- range .Values.dataexchange.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-dx
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}-dx
              servicePort: {{ $svcPort }}
              {{- end }}
    {{- end }}
{{- end }}
