name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build and Test
        run: make

      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)

  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - test-suite: TestEthereumE2ESuite
            blockchain-provider: geth
          - test-suite: TestFabricE2ESuite
            blockchain-provider: fabric
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run E2E tests
        env:
          TEST_SUITE: ${{ matrix.test-suite }}
          BLOCKCHAIN_PROVIDER: ${{ matrix.blockchain-provider }}
        run: ./test/e2e/run.sh

      - name: Archive container logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: container-logs
          path: containerlogs/logs.txt
