name: Helm

on:
  release:
    types: [released, prereleased]
  push:
    branches:
      - main
      - helm-oci-chart-publishing
    paths:
      - "deploy/charts/**/*"
  pull_request:
    branches:
      - main
    paths:
      - "deploy/charts/**/*"
jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup helm
        uses: azure/setup-helm@v1
        with:
          version: 3.7.2

      - name: setup chart-testing tool
        uses: helm/chart-testing-action@v2.0.1

      - name: lint chart
        run: ct lint --charts deploy/charts/firefly-helm

      - name: setup kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.11.1

      - name: install cert-manager
        run: |
          kubectl create ns cert-manager || true
          kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.4.0/cert-manager.crds.yaml
          helm repo add jetstack https://charts.jetstack.io || true
          helm install --skip-crds -n cert-manager cert-manager jetstack/cert-manager --wait
          kubectl apply -n cert-manager -f deploy/manifests/tls-issuers.yaml

      - name: install prom-operator
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts || true
          helm install --set kubeStateMetrics.enabled=false --set nodeExporter.enabled=false --set grafana.enabled=false kube-prometheus prometheus-community/kube-prometheus-stack

      - name: install postgres
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami || true
          helm install --set postgresqlPassword=firef1y --set extraEnv[0].name=POSTGRES_DATABASE --set extraEnv[0].value=firefly postgresql bitnami/postgresql

      - name: run chart integration test
        run: ct install --charts deploy/charts/firefly-helm

      - name: debug k8s
        if: ${{ failure() }}
        run: |
          kubectl get pod -A
  release:
    needs: helm
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags/helm-v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup helm
        uses: azure/setup-helm@v1
        with:
          version: 3.7.2

      - name: helm push
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u $GITHUB_ACTOR --password-stdin
          helm chart save deploy/charts/firefly-helm ghcr.io/hfuss/firefly-helm:${TAG}
          helm chart push ghcr.io/hfuss/firefly-helm:${TAG}
        env:
          HELM_EXPERIMENTAL_OCI: "1"
