name: Solidity Tests

on:
  pull_request:
    branches: [main]

jobs:
  solidity-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: npm ci
        working-directory: ./smart_contracts/ethereum/solidity_firefly
      - run: npm run test
        working-directory: ./smart_contracts/ethereum/solidity_firefly
