{{- if .Values.core.jobs.postgresMigrations.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "firefly.fullname" . }}-{{ .Values.core.image.tag | default (printf "v%s" .Chart.AppVersion) }}-migrations"
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 12000
  template:
    spec:
      containers:
      - name: migration
        image: "{{ .Values.core.image.repository }}:{{ .Values.core.image.tag | default (printf "v%s" .Chart.AppVersion) }}"
        command:
        - sh
        - -ce
        - |
{{ .Files.Get "scripts/ff-db-migrations.sh" | indent 10 }}
        env:
        - name: PSQL_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "firefly.fullname" . }}-config
              key: psql_url
      restartPolicy: Never
{{- end }}
