{{- if .Values.config.registrationJob -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "firefly.fullname" . }}-{{ .Values.config.organizationName | lower }}-registration"
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 12000
  template:
    spec:
      containers:
      - name: migration
        image: "{{ .Values.core.image.repository }}:{{ .Values.core.image.tag | default .Chart.AppVersion }}"
        command:
        - sh
        - -ce
        - |
{{ (.Files.Glob "scripts/ff-registration.sh") | indent 10 }}
        env:
        - name: PSQL_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "firefly.fullname" . }}-config
              key: psql_url
      restartPolicy: Never
{{- end }}
