{{- if .Values.config.registrationJob -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "firefly.fullname" . }}-{{ .Values.config.organizationName | lower }}-registration"
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 12000
  template:
    spec:
      containers:
      - name: registration
        image: "{{ .Values.core.image.repository }}:{{ .Values.core.image.tag | default .Chart.AppVersion }}"
        command:
        - sh
        - -ce
        - |
{{ .Files.Get  "scripts/ff-registration.sh" | indent 10 }}
        env:
        - name: FF_URL
          value: "http://{{ include "firefly.fullname" . }}:{{ .Values.core.service.httpPort }}"
      restartPolicy: Never
{{- end }}
